version: '3.7'

services:
  swagger:
    container_name: lamp-swagger
    build:
      context: './swagger/'
    volumes:
      - ./code/swagger/openapi.yaml:/usr/share/nginx/html/openapi.yaml
      - ./swagger/openapi.html:/usr/share/nginx/html/openapi.html
    networks:
      - frontend
    ports:
      - 8080:8080
  mysql:
    image: mysql:latest
    container_name: lamp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB
      MYSQL_USER: api
      MYSQL_PASSWORD: password
    volumes:
      - ./code/mysql/:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - 3306:3306
  php:
    container_name: vantage_php
    build: 
      context: './php/'
    networks:
      - backend
    volumes:
      - ./code/php/:/var/www/html
      - ./php/:/usr/local/etc/php/
  apache:
    container_name: lamp-apache
    build: './apache'
    depends_on: 
      - php
      - mysql
    volumes:
      - ./code/apache/index.html:/var/www/html/index.html
    networks:
      - frontend
      - backend
    ports:
      - 80:80
networks:
  frontend:
  backend: